const postCategories = [
  "Science",
  "Medical",
  "AI",
  "Technology",
  "Data Science",
  "Machine Learning",
  "Deep Learning",
  "Cloud Computing",
  "Cybersecurity",
  "Blockchain",
  "Quantum Computing",
  "Robotics",
  "Biotechnology",
  "Physics",
  "Chemistry",
  "Astronomy",
  "Mathematics",
  "Engineering",
  "Civil Engineering",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Software Engineering",
  "Web Development",
  "Mobile Development",
  "DevOps",
  "UI UX Design",
  "Product Design",
  "Product Management",
  "Startup",
  "Business",
  "Finance",
  "Investing",
  "Economics",
  "Marketing",
  "Digital Marketing",
  "SEO",
  "Content Strategy",
  "Social Media",
  "Leadership",
  "Career",
  "Productivity",
  "Education",
  "E-learning",
  "Research",
  "Psychology",
  "Mental Health",
  "Wellness",
  "Fitness",
  "Nutrition",
  "Food",
  "Travel",
  "Lifestyle",
  "Parenting",
  "Relationships",
  "Culture",
  "History",
  "Politics",
  "Law",
  "Environment",
  "Climate",
  "Sustainability",
  "Agriculture",
  "Energy",
  "Automotive",
  "Space Tech",
  "Gaming",
  "Esports",
  "Entertainment",
  "Movies",
  "Music",
  "Photography",
  "Design Systems",
  "Architecture",
  "Interior Design",
  "Fashion",
  "Art",
  "Writing",
  "Poetry",
  "Journalism",
  "Books",
  "Open Source",
  "Programming",
  "JavaScript",
  "Python",
  "Java",
  "C Plus Plus",
  "Go",
  "Rust",
  "Databases",
  "MongoDB",
  "SQL",
  "API Design",
  "Microservices",
  "System Design",
  "Testing",
  "Automation",
  "No Code",
  "Low Code",
  "Freelancing",
  "Remote Work",
  "Community",
  "Personal Growth",
  "General",
];

export default postCategories;
